//
//  WATokenFieldViewStyleKit.m
//  WATokenFieldView
//
//  Created by Wendy Abrantes on 12/09/2015.
//  Copyright (c) 2015 ABRANTES DIGITAL LTD. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "WATokenFieldViewStyleKit.h"


@implementation WATokenFieldViewStyleKit

#pragma mark Cache

static UIImage* _imageOfTokenBackgroundHighlighted = nil;

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawTokenBackgroundHighlighted
{

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(2, 2, 36, 52) cornerRadius: 6];
    [UIColor.grayColor setFill];
    [rectanglePath fill];
}

#pragma mark Generated Images

+ (UIImage*)imageOfTokenBackgroundHighlighted
{
    if (_imageOfTokenBackgroundHighlighted)
        return _imageOfTokenBackgroundHighlighted;

    UIGraphicsBeginImageContextWithOptions(CGSizeMake(40, 56), NO, 0.0f);
    [WATokenFieldViewStyleKit drawTokenBackgroundHighlighted];

    _imageOfTokenBackgroundHighlighted = [[UIGraphicsGetImageFromCurrentImageContext() resizableImageWithCapInsets: UIEdgeInsetsMake(9, 8, 9, 9) resizingMode: UIImageResizingModeStretch] imageWithRenderingMode: UIImageRenderingModeAlwaysTemplate];
    UIGraphicsEndImageContext();

    return _imageOfTokenBackgroundHighlighted;
}

#pragma mark Customization Infrastructure

- (void)setTokenBackgroundHighlightedTargets: (NSArray*)tokenBackgroundHighlightedTargets
{
    _tokenBackgroundHighlightedTargets = tokenBackgroundHighlightedTargets;

    for (id target in self.tokenBackgroundHighlightedTargets)
        [target setImage: WATokenFieldViewStyleKit.imageOfTokenBackgroundHighlighted];
}


@end
